# version: '1'

# services:
#   mongo:
#     image: mongo

#   server:
#     image: td_server:1.0.1
#     platform: linux/amd64
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#     - 8000:8000

#   client:
#     image: td_client:1.0.1
#     platform: linux/amd64
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#     - 8501:8501


version: '1'

services:
  mongo:
    image: mongo

  server:
    image: maximilien10/mlops_server:1.0.1
    container_name: mlops_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - 8000:8000

  client:
    image: maximilien10/mlops_client:1.0.1
    container_name: mlops_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
    - 8501:8501