version: '1'

services:
  mongo:
    image: mongo

  server:
    image: td_server:1.0.1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - 8000:8000

  client:
    image: td_client:1.0.1
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
    - 8501:8501